---
title: "DBA3702 Assignment 1"
output: html_document
date: "18 August 2021"
---

## Question 1

```{r}
library('scales')
library('stringr')

#Question 1.1
sales <- c(1736134, 10034,1003948,209445,98878.76,398454,777734.12,1039489.34,293894,9834,9384754.65)

#converting into currency 
convSales <- dollar(sales)

#adding names to vector elements
numOfCust <- length(sales)
vname <- c("customer")
cusId <- str_pad(1:numOfCust, 2, pad = '0')
vname <- paste(vname, cusId, sep="")
names(convSales) <- vname
convSales

#Question 1.2
category <- c()

for(val in sales) {
  if(val > 1000000) {
    category <- c(category, "VVIC")
  } else if (val >= 100000 & val <= 1000000) {
    category <- c(category, "VIC")
  } else {
    category <- c(category, "IC")
  }
}

# For checking:
# convSales
category

```
## Question 2

```{r}

n <- 5
matrix(c(2:n^2,1), ncol = n, byrow = T)

```
## Question 3

```{r}
countries <- "Athens (Greece), Paris (France), St. Louis (United States), London (England), Stockholm (Sweden), Berlin (Germany) [cancelled], Antwerp (Belgium), Paris (France), Amsterdam (Netherlands), Los Angeles (United States), Berlin (Germany), Tokyo (Japan) [cancelled], London (England) [cancelled], London (England), Helsinki (Finland), Melbourne (Australia), Rome (Italy), Tokyo (Japan), Mexico City (Mexico), Munich (West Germany), Montreal (Canada), Moscow (Soviet Union), Los Angeles (United Statesz), Seoul (South Korea), Barcelona (Spain), Atlanta (United States), Sydney (Australia), Athens (Greece), Beijing (China), London (England), Rio de Janeiro (Brazil), Tokyo (Japan)"

#alternative: countries <- str_remove_all(countries, "\\s*\\([^\\)]+\\)")
#remove countries that are cancelled: countries <- str_remove_all(countries, "( \\([a-zA-z ]*\\))|(, [,a-zA-z ]* \\([a-zA-z ]*\\) \\[cancelled\\])")
countries <- str_remove_all(countries, "( \\([a-zA-z ]*\\))| \\[cancelled\\]")
countries <- str_split(countries, ", ")
countries <- countries[[1]]

years <- seq(from=1896, by=4, length.out=length(countries))
countries <- paste(countries, "Olympics", years, sep = " ")
countries


```

